#!/usr/bin/env bash

 # The  rhyme  script is a simple wrapper around the  rhyme.py  script. It activates the virtual environment and runs the script with the arguments passed to it. 
 # The  rhyme.py  script is the main script that does the work. It uses the  requests  library to make a request to the  Datamuse API and prints the results. 

set -e

# cd ~/code/tigoss/rhyme-cli
. ./bin/activate

python3 rhyme.py "$@"
 
